defaults:
 - dataset@lob_dataset_kwargs.dataset_kwargs: mel_20-mpl_20-m_p
 - dataset@ts_dataset_kwargs.dataset_kwargs: rl-mel_20-mpl_20-h-v-l-no_norm
 - dataset@rl_dataset_kwargs.dataset_kwargs: rl-mel_20-mpl_20-action-no_norm
 - dataset@trades_dataset_kwargs.dataset_kwargs: rl-mel_20-mpl_20-action-no_norm
 - _self_


start: "2023-05-02T00:00:00+00:00"
stop: "2023-05-30T00:00:00+00:00"
benchmark_dir: backtest_online_3
update_all: false
plot_all: false
plot_all_curves: false
update_lob: false
update_trades_dataset: false
update_rl_dataset: false
update_ts_dataset: false
update_trades_backtest: false
update_rl_backtest: false
update_ts_backtest: false
update_trades_signature: true
update_rl_signature: true
update_ts_signature: true
plot_trades: false
plot_trades_curves: false
plot_rl: false
plot_rl_curves: false
plot_ts: false
plot_ts_curves: false
plot_backtest_html: false
plot_trades_signatures: false
plot_rl_signatures: false
plot_ts_signatures: false
plot_total_signatures: true
strategy_kwargs:
  size: 400
  unit_size: 1e-6  # Î¼BTC
bt_kwargs:
  cash: 12
  commission: 0.0
  margin: 1.0
  trade_on_close: false
  hedging: false
  exclusive_orders: false
trades_signature_kwargs:
  prefix: "-trades-"
  g_col: strategy
  resample_kwargs: 
    rule: 1S
  window: 10T
  calculate_kwargs:
    bins: 600
    kinds: [ diff, relative, ratio, lograt ]
    lines: ['mean', 'median']
rl_signature_kwargs:
  prefix: "-rl-"
  g_col: model
  window: 10T
  resample_kwargs: 
    rule: 1S
  calculate_kwargs:
    bins: 600
    kinds: [ diff, relative, ratio, lograt ]
    lines: ['mean', 'median']
ts_signature_kwargs:
  prefix: "-ts-"
  g_col: model
  window: 10T
  resample_kwargs: 
    rule: 1S
  calculate_kwargs:
    bins: 600
    kinds: [ diff, relative, ratio, lograt ]
    lines: ['mean', 'median']
histogram_kwargs:
  figsize: [8, 6]
  bins: 600
  cmap: hot
  kinds: [ diff, relative, ratio, lograt ]
  lines: ['mean', 'median', '0.25', '0.75', '0.05', '0.95']
  plot_histogram: true
  plot_html: true
layout_kwargs:
  plot_bgcolor: "#212121"  # darkest grey
  template: plotly_dark
  showlegend: false
signature_layout_kwargs:
  plot_bgcolor: "#212121"  # darkest grey
  template: plotly_dark
  width: 800
  height: 600
  legend: {x: 0, y: -2.0}
curves_layout_kwargs:
  plot_bgcolor: "#212121"  # darkest grey
  template: plotly_dark
  autosize: false
  width: 1920
  height: 1080
  legend: {x: 0, y: -2.0}
lob_dataset_kwargs:
  quant: 3e+9
  replace_nan: ~
  split: ~
  merge_features: false
  return_all_df: true
  verbose: false
  agents:
    tusd:
      class: InfluxDBDataset2
      batch_size: 86400e+9
      client:
        timeout: 100000
      topic: lob
      key: binance-btc-tusd
ts_dataset_kwargs:
  quant: 3e+9
  # start: -1800  # number of quants
  # stop: ~  # now
  replace_nan: ~
  split: ~
  merge_features: false
  return_all_df: true
  verbose: true
  agents:
    tusd:
      class: InfluxDBDataset2
      batch_size: 86400e+9
      client:
        timeout: 100000
      topic: prediction
      key: binance-btc-tusd
      filters:
        model: influxdb-mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat-no_group
      pivot:
        index: ['timestamp', 'exchange', 'base', 'quote', 'quant', 'feature', 'target', 'model', 'version']
        columns: ['horizon']
rl_dataset_kwargs:
  quant: 3e+9
  # start: -1800  # number of quants
  # stop: ~  # now
  replace_nan: ~
  split: ~
  merge_features: false
  return_all_df: true
  verbose: true
  agents:
    tusd:
      class: InfluxDBDataset2
      batch_size: 86400e+9
      client:
        timeout: 100000
      topic: prediction
      key: binance-btc-tusd
      filters:
        model: "/ppo.*/"
        # model: ppo-binance-btc-tusd-20-h-v-l-min_max_all-last_1w-tune
        # model: ppo-binance-btc-tusd-20-h_20-v-l-std_all-last_30m   
trades_dataset_kwargs:
  quant: 3e+9
  # start: -1800  # number of quants
  # stop: ~  # now
  replace_nan: ~
  split: ~
  merge_features: false
  return_all_df: true
  verbose: false
  agents:
    tusd:
      class: InfluxDBDataset2
      batch_size: 86400e+9
      client:
        timeout: 100000
      topic: metric
      key: binance-btc-tusd
      filters:
        model: ~

