defaults:
  - _self_

agents:
  btc_usdt:
    class: DeltaInfluxDB
    client:
      verify_ssl: false
      timeout: 3000000
    write_api:
      write_options:
        batch_size: 3000
        flush_interval: 10000
    feature: rat-ema-qv-vwap_20
    kind: rat
    verbose: true
    start: "2023-02-27T00:00:00+00:00"
    stop: "2023-04-01T00:00:00+00:00"
    size: ~
    quant: 3.0e+9
    delay: 86400e+9  # 1 day
    # delay: 0.0
    batch_size: 3600e+9
    watermark: 15.0e+9  # min 2*quant
    depth: 20
    topic_keys:
      lob: [ binance-btc-usdt ]
      trade: [ binance-btc-usdt ]
    vwaps:
      - quantities: [ 0.001, 0.01, 0.1, 1, 10, ~ ]
        currency: base
      - quantities: [ 10, 100, 1000 ]
        currency: quote
    emas:
      - columns: [ '^m_p$', '^a_v$', '^b_v$', '^o_v$', '^t_p$', '^t_v$', '^t_v_b$', '^t_v_s$', '^vwap.*' ]
        alphas: [ 1.0, 0.1, 0.01, 1e-3, 1e-4 ]
    deltas:
      - shift: 1 
        columns_up: [ '^m_p$', '^a_v$', '^b_v$', '^o_v$', '^t_p$', '^t_v$', '^t_v_b$', '^t_v_s$', '^vwap.*', '^ema_.*' ]
        self_only: True
      - shift: 0
        columns_up: [ '^ema_.*m_p$', '^ema_.*t_p$', '^ema_.*-vwap_mid' ]
        columns_bottom: [ '^ema_.*m_p$' ]
      - shift: 0
        columns_up: [ '^ema_.*a_v$' ]
        columns_bottom: [ '^ema_.*b_v$' ]
      - shift: 0
        columns_up: [ '^ema_.*t_v_b$' ]
        columns_bottom: [ '^ema_.*t_v_s$' ]
      - shift: 0
        columns_up: [ '^ema_.*t_v$' ]
        columns_bottom: [ '^ema_.*t_v$' ]
      - shift: 0
        columns_up: [ '^ema_.*o_v$' ]
        columns_bottom: [ '^ema_.*o_v$' ]