defaults:
 - dataset@create_dataset_kwargs.dataset_kwargs: mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat-no_group
 - _self_
 
kind: ~  # set ~ to constant model
model_name: influxdb-mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat-no_group
model_version: 1
model_stage: ~
verbose: false
horizons: [ 5, 10, 15, 20 ]
predict_kwargs:
  return_index: true
  mode: quantiles  # prediction or quantiles
interpret_kwargs:
  attention_prediction_horizon: 20  # set ~ to interpret all items from horizons field
interpret_attention: True
interpret_importance: True
create_dataset_kwargs:
  verbose: false
  start: "2023-03-21T02:30:00+00:00"
  stop: "2023-03-21T02:40:00+00:00"
  quant: 3e9
  watermark: 120e9
  replace_nan: 1.0
  split: ~
  dataset_kwargs: 
    predict_mode: true
  agents:
    influxdb: 
      class: StreamDatasetInfluxDB
      batch_size: 60e9
      client:
        verify_ssl: false
        timeout: 3000000
      verbose: false
      feature_keys:
        rat-ema-qv-vwap_20: [ binance-btc-usdt ]
agents:
  prediction:
    class: InfluxDB
    client:
      verify_ssl: false
      timeout: 3000000
    producers:
      p_1:
        topic_keys:
          prediction: [ binance-btc-usdt ]
  metric:
    class: InfluxDB
    client:
      verify_ssl: false
      timeout: 3000000
    producers:
      p_1:
        topic_keys:
          metric: [ binance-btc-usdt ]