defaults:
 - partitioner@create_dataset_kwargs.agents.a_1.consumer.partitioners.feature: feature
 - dataset@create_dataset_kwargs.dataset_kwargs: mid-lograt-kafka-binance-btc-usdt
 - _self_
 
kind: occasional
parent_name: ~
parent_version: ~
parent_stage: ~
model_name: kafka-mid-lograt-tft-binance-btc-usdt
create_dataset_kwargs:
  verbose: false
  quant: 3.0e+9
  size: 1200
  replace_nan: 0.0
  split: 0.8
  agents:
    a_1: 
      class: KafkaDataset
      verbose: false
      topics: [ feature ]
      executor:
        class: ProcessPoolExecutor
        max_workers: 1
      feature_keys:
        Delta-default-lograt: [ binance-btc-usdt ]
      consumer:
        bootstrap_servers: "kafka:9092"
dataloader_kwargs:
  train:
    train: true
    num_workers: 0
    batch_size: 8
  val:
    train: false
    num_workers: 0
    batch_size: 8
model_kwargs:
  class: TemporalFusionTransformer
  learning_rate: 0.0078125
  hidden_size: 8
  attention_head_size: 1
  dropout: 0
  hidden_continuous_size: 8
  lstm_layers: 1
  # output_size: 7  # Inferred from loss
  loss:
    class: QuantileLoss
  log_interval: 0
  reduce_on_plateau_patience: 2
  reduce_on_plateau_reduction: 2
  reduce_on_plateau_min_lr: 1.0e-10
  weight_decay: 0
trainer_kwargs:
  max_epochs: 8
  accelerator: cpu  # gpu
  devices: ~
  gradient_clip_val: 0
  log_every_n_steps: 50
  limit_train_batches: ~
  logger:
  - class: MLFlowLogger
    experiment_name: ~  # default to model_name
    # artifact_location: ~  # default to model_name (See https://github.com/Lightning-AI/lightning/issues/1113)
    # tracking_uri: http://mlflow:5000  # default to MLFLOW_TRACKING_URI
  callbacks:
  - class: DeviceStatsMonitor
    cpu_stats: true
  - class: LearningRateMonitor
    logging_interval: ~
    log_momentum: true
  - class: ModelCheckpoint
    monitor: val_loss
    filename: '{epoch}-{step}-{val_loss:.3f}'
    save_last: true
    save_top_k: 1
  - class: EarlyStopping
    monitor: val_loss
    min_delta: 0
    patience: 4
    verbose: false
    mode: min