defaults:
 - dataset@create_dataset_kwargs.dataset_kwargs: mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat
 - _self_
 
kind: occasional
parent_name: ~
parent_version: ~
parent_stage: ~
model_name: influxdb-mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat
create_dataset_kwargs:
  verbose: true
  quant: 3.0e+9
  start: "2022-07-01T00:00:00+00:00"
  stop: "2022-07-07T00:00:00+00:00"
  replace_nan: 1.0
  split: 0.8
  agents:
    influxdb: 
      class: InfluxdbDataset
      batch: 86400.0e+9  # day
      verbose: true
      topics: [ feature ]
      executor:
        class: ProcessPoolExecutor
        max_workers: 1
      feature_keys:
        rat-ema-qv-vwap_20: [ binance-btc-usdt ]
      client:
        timeout: 200000
        verify_ssl: false
dataloader_kwargs:
  train:
    train: true
    num_workers: 16
    batch_size: 128
  val:
    train: false
    num_workers: 16
    batch_size: 128
model_kwargs:
  class: TemporalFusionTransformer
  # learning_rate: 0.03125  # 2^-6 1/32 
  learning_rate: 0.00390625  # 2^-8 1/256 
  # learning_rate: 0.0009765625  # 2^-10 1/1024
  # learning_rate: 0.0000152587890625  # 2^-16 1/65536 
  hidden_size: 8
  attention_head_size: 1
  dropout: 0.1
  hidden_continuous_size: 8
  lstm_layers: 1
  # output_size: 7  # Inferred from loss
  loss:
    class: QuantileLoss
  log_interval: 0
  reduce_on_plateau_patience: 2
  reduce_on_plateau_reduction: 2
  reduce_on_plateau_min_lr: 1.0e-10
  weight_decay: 0
  logging_metrics:
  - SMAPE
  - MAE
  - RMSE
  - MAPE
  - class: ROR
    target_kind: rat
    direction: all
    mask_kind: none
  - class: ROR
    target_kind: rat
    direction: all
    mask_kind: max
  - class: ROR
    target_kind: rat
    direction: pos
    mask_kind: max
  - class: ROR
    target_kind: rat
    direction: neg
    mask_kind: max
  - class: ROR
    target_kind: rat
    direction: pos
    mask_kind: none
  - class: ROR
    target_kind: rat
    direction: neg
    mask_kind: none
  - class: ROR
    target_kind: rat
    direction: pos
    mask_kind: all
  - class: ROR
    target_kind: rat
    direction: neg
    mask_kind: all
  - class: ROR
    target_kind: rat
    direction: pos
    mask_kind: last
  - class: ROR
    target_kind: rat
    direction: neg
    mask_kind: last
trainer_kwargs:
  max_epochs: 256
  accelerator: gpu  # cpu
  devices: [ 0 ]
  gradient_clip_val: 0
  gradient_clip_algorithm: norm  # norm or value
  track_grad_norm: 2
  log_every_n_steps: 300
  # limit_train_batches: 5
  logger:
  - class: MLFlowLogger
    experiment_name: ~  # default to model_name
  callbacks:
  # - class: DeviceStatsMonitor
  #   cpu_stats: true
  # - class: StochasticWeightAveraging
  #   annealing_epochs: 2
  #   annealing_strategy: cos
  #   device: null
  #   swa_epoch_start: 2
  #   swa_lrs: 0.01
  - class: LearningRateMonitor
    logging_interval: ~
    log_momentum: true
  - class: ModelCheckpoint
    monitor: val_loss
    filename: '{epoch}-{step}-{val_loss:.3f}'
    save_last: true
    save_top_k: 1
  - class: EarlyStopping
    monitor: val_loss
    min_delta: 0
    patience: 9
    verbose: false
    mode: min