version: '3.3'

services:
  predict_mlflow_kafka_influxdb_mid_lograt_tft_binance_btc_usdt_lr_7_bs_7_1w_2023_5_ext:
    image: ccf
    # container_name: predict_mlflow_kafka_influxdb_1d
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - db
      - mlflow
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/predict_mlflow.py, -cd, conf, -cn, predict-mlflow-kafka-influxdb-mid-lograt-tft-binance-btc-usdt-lr_7-bs_7-1w-2023_5-ext ]
    env_file:
      - .env.secret.model
    environment:
      PYTHONPATH: /app/src
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_TRACKING_USERNAME: ccf
    volumes:
      # - binance_btc_usdt:/app/work
      - ../work:/app/work
    restart: always
      
networks:
  db:
    driver: bridge
  mlflow:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
