version: '3.3'

services:
  predict_local_kafka_influxdb:
    image: ccf
    # container_name: predict_kafka
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - db
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/predict.py, -cd, conf, -cn, predict-mid-lograt-tft-kafka-binance-btc-usdt ]
    environment:
      PYTHONPATH: /app/src
    volumes:
      # - binance_btc_usdt:/app/work
      - ../work:/app/work
    restart: always
    # healthcheck:  # Restart service every interval time to replace model on last tuned by train FIXME MLflow
    #   test: ["CMD", "exit", "1"]
    #   interval: 1m
    #   timeout: 0s
    #   retries: 1
    #   start_period: 0s
      
networks:
  db:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
