version: '3.3'

services:
  trade-kafka-binance-btc-tusd-fast-rl-3:
    image: ccf_trade_kafka
    build:
      context: ..
      dockerfile: docker/Dockerfile.trade_kafka
    stop_signal: SIGTERM
    stop_grace_period: 15s
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      - db
      - mlflow
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/trade_kafka.py, -cd, conf, -cn, trade-kafka-binance-btc-tusd-fast-rl-3 ]
    env_file:
      - .env.secret.trade.binance.mainnet
    environment:
      PYTHONPATH: /app/src
      PYTHONUNBUFFERED: 1
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_TRACKING_USERNAME: ccf
    volumes:
    # - binance_btc_usdt:/app/work
      - ../work:/app/work
    restart: always
      
networks:
  db:
    driver: bridge
  mlflow:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
