version: '3.3'

services:
  predict-interpret-mlflow-kafka-influxdb-mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat-no_group-binance-btc-tusd:
    image: ccf
    # container_name: predict_mlflow_kafka_influxdb_1d
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: 10m
    networks:
      - db
      - mlflow
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/predict_interpret_mlflow.py, -cd, conf, -cn, predict-interpret-mlflow-kafka-influxdb-mid-rat-ema_vwap_base_10_1_1-mel_20-mpl_20-no_cat-no_group-binance-btc-tusd ]
    env_file:
      - .env.secret.model
    environment:
      PYTHONPATH: /app/src
      PYTHONUNBUFFERED: 1
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_TRACKING_USERNAME: ccf
    volumes:
      # - binance_btc_usdt:/app/work
      - ../work:/app/work
    restart: always
      
networks:
  db:
    driver: bridge
  mlflow:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
