version: '3.3'

services:
  extract_features-kafka-binance-btc-usdt-rat-ema-qv-vwap_20:
    image: ccf
    # container_name: get_data-kafka-binance-btc-usdt-20
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - db
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/extract_features.py, -cd, conf, -cn, extract_features-kafka-binance-btc-usdt-rat-ema-qv-vwap_20 ]
    environment:
      PYTHONPATH: /app/src
    restart: always
      
networks:
  db:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
