version: '3.3'

services:
  ui:
    image: ccf
    container_name: ui_binance_btc_usdt
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - db
    working_dir: /app/work
    entrypoint: [ streamlit ]
    ports:
      - "8501:8501"
    command: [ run, ../src/ccf/apps/ui.py, conf/ui-mid-lograt-tft-kafka-binance-btc-usdt.yaml ]
    environment:
      PYTHONPATH: /app/src
    # volumes:
    #   # - binance_btc_usdt:/app/work
    #   - ../work:/app/work
    restart: always
      
networks:
  db:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
