version: '3.3'

services:
  get_data-kafka-binance-eth-tusd-lob-20:
    image: ccf
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - db
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/get_data.py, -cd, conf, -cn, get_data-kafka-binance-eth-tusd-lob-20 ]
    environment:
      PYTHONPATH: /app/src
    restart: always
      
networks:
  db:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
