version: '3.3'

services:
  predict.rl.ppo-binance-btc-tusd-20-h_20-v-a-last_30m:
    image: ccf
    # container_name: predict_mlflow_kafka_influxdb_1d
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - db
      - mlflow
    working_dir: /app/work
    entrypoint: [ python ]
    command: [ ../src/ccf/predict_rl.py, -cd, conf, -cn, predict-rl-kafka-binance-btc-ppo-binance-btc-tusd-20-h_20-v-a-last_30m ]
    env_file:
      - .env.secret.model
    environment:
      PYTHONPATH: /app/src
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_TRACKING_USERNAME: ccf
    volumes:
      # - binance_btc_usdt:/app/work
      - ../work:/app/work
    restart: always
      
networks:
  db:
    driver: bridge
  mlflow:
    driver: bridge
    
# volumes:
#   binance_btc_usdt:
